// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYcMfHl6LP6mJiTyxQOQLc53vfvVcdJGw',
    appId: '1:548379745638:web:cdd078c1ccb13073ae3ca7',
    messagingSenderId: '548379745638',
    projectId: 'sapp-50b98',
    authDomain: 'sapp-50b98.firebaseapp.com',
    storageBucket: 'sapp-50b98.firebasestorage.app',
    measurementId: 'G-309KJNEG9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhiIbe4if7pQqt7lXajG01M-9mWLo5qmQ',
    appId: '1:548379745638:android:adebdf2b341f64e6ae3ca7',
    messagingSenderId: '548379745638',
    projectId: 'sapp-50b98',
    storageBucket: 'sapp-50b98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKYqQQPfZDQCey8YHbSGTmRBf20c07zq8',
    appId: '1:548379745638:ios:344c94b88fb62cadae3ca7',
    messagingSenderId: '548379745638',
    projectId: 'sapp-50b98',
    storageBucket: 'sapp-50b98.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKYqQQPfZDQCey8YHbSGTmRBf20c07zq8',
    appId: '1:548379745638:ios:344c94b88fb62cadae3ca7',
    messagingSenderId: '548379745638',
    projectId: 'sapp-50b98',
    storageBucket: 'sapp-50b98.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYcMfHl6LP6mJiTyxQOQLc53vfvVcdJGw',
    appId: '1:548379745638:web:25921cdb1a5c4e72ae3ca7',
    messagingSenderId: '548379745638',
    projectId: 'sapp-50b98',
    authDomain: 'sapp-50b98.firebaseapp.com',
    storageBucket: 'sapp-50b98.firebasestorage.app',
    measurementId: 'G-K92LPJPMP4',
  );
}
